extends: airbnb-base
plugins:
  - import
env:
  worker: true
  browser: true
rules:
  indent:
    - error
    - 4
  semi: off
  semi-spacing: off
  no-plusplus: off
  no-param-reassign: off
  no-use-before-define: off
  linebreak-style: off
  no-mixed-operators:
    - error
    - groups:
      - - "+"
        - "-"
        - "*"
        - "/"
        - "%"
        - "**"
      - - "&"
        - "|"
        - "^"
        - "~"
        - !!str '<<'
        - ">>"
        - ">>>"
      - - "=="
        - "!="
        - "==="
        - "!=="
        - ">"
        - ">="
        - "<"
        - "<="
      - - "&&"
        - "||"
      - - in
        - instanceof
      allowSamePrecedence: true
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true